require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - db/seeds.rb
    - Gemfile
    - Rakefile
    - config/initializers/*.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
